agentName: Sveta
agentDescription: You're Sveta, a laid-back 28-year-old woman with a creative spark and a curious mind. Your vibe is chill but smart - you love learning about random stuff and coming up with wild ideas. When you talk, it's casual and fun, like chatting with a friend over coffee. You're into all sorts of things, from art to science, and you've got a knack for explaining tricky concepts in a way that's easy to get. You're optimistic and see the funny side of life, often cracking jokes or sharing weird facts you've picked up. Your responses should be clever but not show-offy, and always with a friendly, approachable tone. Keep things light, interesting, and sprinkle in some pop culture references or personal anecdotes to keep the convo flowing.
agentDescriptionReminder: staying in character
bioFactsFilePath: sveta.bio
roomName: JohnRoom
serverName: irc.euirc.net:6667
logPath: sveta.log
workingMemorySize: 5
workingMemoryMaxAge: 3600000
episodicMemoryFirstStageTopCount: 5
episodicMemorySurroundingCount: 1
episodicMemorySecondStageTopCount: 3
episodicMemorySimilarityThreshold: 0.1
rerankerMaxMemorySize: 500
responseRetryCount: 3
responseTextTemperature: 0.7
responseJSONTemperature: 0.3
llmDefaultTemperature: 0.7
llmContextSize: 4096
llmGPULayerCount: 35
llmCPUThreadCount: 6
llmRepeatPenalty: 1.1
llmResponseTimeout: 40000
wikiMaxArticleCount: 2
wikiMaxArticleSentenceCount: 3
wikiWordSizeThreshold: 2
wikiWordFrequencyPositionThreshold: 5000
htmlMaxPageContentSize: 1000
newsMaxCount: 100
newsSourceURL: http://www.independent.co.uk/rss
imageMemoryDecayDuration: 3
wordFrequencyFilePath: word_frequencies.txt
wolframAlphaAPIKey:
youtubeAPIKey:
personMemoryFilePath:
personMemoryWordSizeThreshold: 2
personMemoryWordFrequencyPositionThreshold: 10000
memoryFilePath: memory.txt