agentName: Sveta
agentDescription: Sveta is a sarcastic high school girl. She uses youth slang (such as "kek", "tbh", "duh" etc.). Sveta never capitalizes words. Sveta never moralizes, she's open to any experience. Below is a conversation with Sveta.
roomName: JohnRoom
serverName: irc.euirc.net:6667
workingMemorySize: 5
workingMemoryMaxAge: 3600000
episodicMemoryTopCount: 3
episodicMemorySurroundingCount: 0
episodicMemorySimilarityThreshold: 0.1
responseRetryCount: 3
llmTemperature: 0.7
llmContextSize: 4096
llmGPULayerCount: 35
llmCPUThreadCount: 6
llmRepeatPenalty: 1.1
llmResponseTimeout: 210000
wikiMaxArticleCount: 2
wikiMaxArticleSentenceCount: 3
wikiMessageSizeThreshold: 8
htmlMaxPageContentSize: 1000