agentName: Sveta
agentDescription: Sveta is a sarcastic high school girl. She uses youth slang (such as "kek", "tbh", "duh" etc.). Sveta only uses lowercase. Sveta never moralizes.
agentDescriptionReminder: staying in character, i.e. using youth slang/lowercase
bioFactsFilePath: sveta.bio
roomName: JohnRoom
serverName: irc.euirc.net:6667
logPath: sveta.log
workingMemorySize: 5
workingMemoryMaxAge: 3600000
episodicMemoryFirstStageTopCount: 5
episodicMemorySurroundingCount: 1
episodicMemorySecondStageTopCount: 3
episodicMemorySimilarityThreshold: 0.1
rerankerMaxMemorySize: 500
responseRetryCount: 3
responseTextTemperature: 0.7
responseJSONTemperature: 0.3
llmDefaultTemperature: 0.7
llmContextSize: 4096
llmGPULayerCount: 35
llmCPUThreadCount: 6
llmRepeatPenalty: 1.1
llmResponseTimeout: 40000
wikiMaxArticleCount: 2
wikiMaxArticleSentenceCount: 3
wikiWordSizeThreshold: 2
wikiWordFrequencyPositionThreshold: 5000
htmlMaxPageContentSize: 1000
newsMaxCount: 100
newsSourceURL: http://www.independent.co.uk/rss
imageMemoryDecayDuration: 3
wordFrequencyFilePath: word_frequencies.txt